version: '3.1'

services:
  express_app:
    image: vulpecula78/expressapp
    ports:
      - 8080:8080

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
